### ISSUE TITLE
Error in tag("div", list(...)) : could not find function "jscolorInput"

### ISSUE THREAD

**Issue by semiexpert** [yindeng/shinyData#1]
Hi Yindeng,

I have tried to use shinyData from Rstudio following the installation instruction. However, there is an error "Error in tag("div", list(...)) : could not find function "jscolorInput" when shinyData::shinyData().

There was an error in finding "shiny package" in the first trial of installation. I have Shiny package pre-installed before. Did any of the tool detached shiny? Anyway, after re-install shiny, the installation went through. 

Can you help with the above error? Thanks.

Rick

**Comment by yindeng** [comment]
Hi Rick,

Sorry about that inconvenience. "jscolor" is part of ShinySky, but apparently it got removed recently. For a temporary solution, you can install an older version of ShinySky as follows:

`devtools::install_github("AnalytixWare/ShinySky@7031af5906d6ec244859d1ba676a9ca8e1541342")`

I just tested it on my machine and it should work. Let me know if you have any other questions. (Not sure why shiny was detached for you during the first round.)

Yindeng
